package agent

import (
	"fmt"
	"os"
	"time"

	"gopkg.in/yaml.v3"
)

// Config is the agent's full runtime configuration.
// Loaded from a YAML file; individual fields can be overridden via
// environment variables (OBSERVE_<UPPER_FIELD_NAME>).
type Config struct {
	// APIKey is the credential key generated by the aggregator admin.
	APIKey string `yaml:"api_key"`
	// APISecret is the credential secret generated by the aggregator admin.
	APISecret string `yaml:"api_secret"`
	// AggregatorURL is the full URL of the aggregator's push endpoint.
	// Example: https://coco-iam.example.com/api/v1/admin/observe/push
	AggregatorURL string `yaml:"aggregator_url"`
	// PushInterval controls how often metrics are collected and pushed.
	// Default: 180s.
	PushInterval time.Duration `yaml:"push_interval"`
	// BufferDir is where unsent batch files are stored.
	// Default: ./observe-buffer
	BufferDir string `yaml:"buffer_dir"`
	// BufferRetention is the maximum age of a buffered batch file before
	// it is discarded (even if not yet pushed). Default: 24h.
	BufferRetention time.Duration `yaml:"buffer_retention"`
	// Processes lists the Go applications on this machine to monitor.
	Processes []ProcessTarget `yaml:"processes"`
}

// ProcessTarget describes one Go process to scrape runtime metrics from.
type ProcessTarget struct {
	// Name is the human label shown in the UI.
	Name string `yaml:"name"`
	// ScrapeURL is the /debug/vars endpoint of the process.
	// Example: http://localhost:2026/debug/vars
	ScrapeURL string `yaml:"scrape_url"`
}

// LoadConfig reads the YAML file at path and applies env var overrides.
func LoadConfig(path string) (*Config, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read config: %w", err)
	}
	var cfg Config
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("parse config: %w", err)
	}
	applyEnvOverrides(&cfg)
	if err := cfg.validate(); err != nil {
		return nil, err
	}
	return &cfg, nil
}

func applyEnvOverrides(cfg *Config) {
	if v := os.Getenv("OBSERVE_API_KEY"); v != "" {
		cfg.APIKey = v
	}
	if v := os.Getenv("OBSERVE_API_SECRET"); v != "" {
		cfg.APISecret = v
	}
	if v := os.Getenv("OBSERVE_AGGREGATOR_URL"); v != "" {
		cfg.AggregatorURL = v
	}
	if v := os.Getenv("OBSERVE_BUFFER_DIR"); v != "" {
		cfg.BufferDir = v
	}
}

func (c *Config) validate() error {
	if c.APIKey == "" {
		return fmt.Errorf("agent config: api_key is required")
	}
	if c.APISecret == "" {
		return fmt.Errorf("agent config: api_secret is required")
	}
	if c.AggregatorURL == "" {
		return fmt.Errorf("agent config: aggregator_url is required")
	}
	if c.PushInterval <= 0 {
		c.PushInterval = 180 * time.Second
	}
	if c.BufferRetention <= 0 {
		c.BufferRetention = 24 * time.Hour
	}
	if c.BufferDir == "" {
		c.BufferDir = "./observe-buffer"
	}
	return nil
}
